services:
  django1:
    build: .
    container_name: django1
    depends_on:
      - pgbouncer
      - redis
    environment:
      - DATABASE_URL=postgres://hamza:testpassword@pgbouncer:6432/DB_For_scalable_system
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8001:8000"

  django2:
    build: .
    container_name: django2
    depends_on:
      - pgbouncer
      - redis
    environment:
      - DATABASE_URL=postgres://hamza:testpassword@pgbouncer:6432/DB_For_scalable_system
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8002:8000"

  django3:
    build: .
    container_name: django3
    depends_on:
      - pgbouncer
      - redis
    environment:
      - DATABASE_URL=postgres://hamza:testpassword@pgbouncer:6432/DB_For_scalable_system
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8003:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django1
      - django2
      - django3

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: DB_For_scalable_system
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: testpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    environment:
      DATABASE_URL: postgres://hamza:testpassword@db:5432/DB_For_scalable_system
      PGBOUNCER_AUTH_TYPE: trust
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_MAX_CLIENT_CONN: 100
      PGBOUNCER_DEFAULT_POOL_SIZE: 20
      PGBOUNCER_LISTEN_PORT: 6432
    volumes:
      - ./pgbouncer-config/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer-config/userlist.txt:/etc/pgbouncer/userlist.txt  
    depends_on:
      - db
    ports:
      - "6432:6432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
